print('---------------------------------------------------')
print('----------------CALCULO COMBUSTIVEL----------------')
print('---------------------------------------------------')
tempo = float(input('Informe o tempo gasto na viagem (em horas)    : '))
veloc_media = float(input('Informe a velocidade média na viagem (em km)  : '))
distancia = round((tempo*veloc_media),2)
litros_usados = round((distancia/12),2)
print('---------------------------------------------------')
print(f'Tempo de Viagem                     : {tempo} h')
print(f'Velocidade Média                    : {veloc_media} km/h')
print(f'Distância Percorrida                : {distancia} km')
print(f'Quantidade de Litros de Combustível : {litros_usados} l')
print('---------------------------------------------------')